name = "websocket-server"
main = "./src/cf-worker/index.ts"
compatibility_date = "2024-05-12"

[[durable_objects.bindings]]
name = "WEBSOCKET_SERVER"
class_name = "WebSocketServer"

[[migrations]]
tag = "v1"
new_classes = ["WebSocketServer"]
