name: ci

on:
  push:
    branches: ['**']
  pull_request:
    branches: ['**']

jobs:
  lint:
    strategy:
      matrix:
        node-version: [20]
        os: [ubuntu-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: schickling-actions/checkout-and-install@main
      - run: pnpm lint:check

  test:
    strategy:
      matrix:
        node-version: [20]
        os: [ubuntu-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: schickling-actions/checkout-and-install@main
      - run: pnpm build:ts
      - run: pnpm test

  build-example-todomvc:
    strategy:
      matrix:
        node-version: [20]
        os: [ubuntu-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: schickling-actions/checkout-and-install@main
      - run: pnpm build:ts
      - run: pnpm build
        working-directory: examples/todomvc
