name: Fix Lock File and Create PR

on:
  workflow_dispatch:
    inputs:
      base-branch:
        description: 'Base branch to create the PR against'
        required: true
        default: 'main'

jobs:
  fix-lockfile:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
        with:
          ref: ${{ github.event.inputs.base-branch }}
      - name: Install pnpm
        uses: pnpm/action-setup@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: pnpm

      - name: Create new branch
        run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'
          git checkout -b fix-lockfile

      - run: pnpm install --fix-lockfile

      - name: Commit changes
        run: |
          git add pnpm-lock.yaml
          git commit -m 'fix: update pnpm lockfile with pnpm install --fix-lockfile'
          git push origin fix-lockfile

      - name: Create PR
        uses: devops-infra/action-pull-request@v0.5.5
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          source_branch: fix-lockfile
          target_branch: ${{ github.event.inputs.base-branch }}
          title: "Fix: Update PNPM Lockfile"
          body: "**Automated pull request**"
          label: dependencies
          draft: false
